### ISSUE TITLE
Does this support LazyLoad module(s)!

### ISSUE THREAD

**Issue by vrkansagara** [romain-jeannoutot/angular6-breadcrumb#2]
Does this support LazyLoading functionality!

**Comment by romain-jeannoutot** [comment]
Hi !

Why use lazy loading for breadcrumb ?

Thanks.

**Comment by vrkansagara** [comment]
@romain-jeannoutot Kindly re-read the issue title. Thanks.

**Comment by romain-jeannoutot** [comment]
No idea, i didn't test it with lazy loading modules. Thanks.
